name: Deploy to central

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "Deploy: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: false

jobs:

  build:
    uses: ./.github/workflows/ci.yml

  deploy:
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PRIVATE_PASSWORD }}

      - name: Cache Kotlin Konan
        id: cache-kotlin-konan
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan/**/*
          key: kotlin-konan-${{ runner.os }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Check
        run: >-
          ./gradlew publish
                    closeSonatypeStagingRepository
                    -Psigning.gnupg.passphrase='${{secrets.GPG_PRIVATE_PASSWORD}}'
                    -Psigning.gnupg.keyName='${{secrets.GPG_PRIVATE_KEY_ID}}'
                    -PsonatypeUsername='${{secrets.SONATYPE_USERNAME}}'
                    -PsonatypePassword='${{secrets.SONATYPE_PASSWORD}}'
